"$schema" = 'https://starship.rs/config-schema.json'

# format = '$all$directory$character'
add_newline = false
# A minimal left prompt
format = """$os$shell$directory$character"""
palette = "notakrista"
# move the rest of the prompt to the right
right_format = """$all"""

# format = """
# [â–‘â–’â–“](#a3aed2)\
# $os\
# [î‚´](bg:#769ff0 fg:#a3aed2)\
# $directory\
# [î‚´](fg:#769ff0 bg:#394260)\
# $git_branch\
# $git_status\
# [î‚´](fg:#394260 bg:#212736)\
# $nodejs\
# $rust\
# $golang\
# $php\
# $python\
# $java\
# [î‚´](fg:#212736 bg:#1d2230)\
# $time\
# [î‚´ ](fg:#1d2230)\
# $fill\
# $memory_usage\
# $shell\
# $username\
# $hostname\
# \n """


[os]
# style = "bg:#a3aed2 fg:#090c0c"
disabled = false # Disabled by default

[os.symbols]
Alpaquita = "ğŸ”” "
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Android = "ğŸ¤– "
Arch = "ğŸ—ï¸ "
Artix = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ğŸš€ "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Garuda = "ğŸ¦… "
Gentoo = "ğŸ—œï¸ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ğŸ¦ "
Linux = "ğŸ§ "
Mabox = "ğŸ“¦ "
Macos = "ğŸ "
Manjaro = "ğŸ¥­ "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ğŸŒ¿ "
NetBSD = "ğŸš© "
NixOS = "â„ï¸ "
OpenBSD = "ğŸ¡ "
OpenCloudOS = "â˜ï¸ "
openEuler = "ğŸ¦‰ "
openSUSE = "ğŸ¦ "
OracleLinux = "ğŸ¦´ "
Pop = "ğŸ­ "
Raspbian = "ğŸ“ "
Redhat = "ğŸ© "
RedHatEnterprise = "ğŸ© "
Redox = "ğŸ§ª "
Solus = "â›µ "
SUSE = "ğŸ¦ "
Ubuntu = "ğŸ¯ "
Unknown = "â“ "
Windows = "ğŸªŸ "

# [directory]
# style = "fg:#e3e5e5 bg:#769ff0"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "â€¦/"

[git_branch]
symbol = "ï˜"
# style = "bg:#394260"
format = '[ on $symbol $branch ]($style)'

[git_status]
# style = "bg:#394260"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = "îœ˜"
# style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
# style = "bg:#212736"
format = '[ $symbol($profile )(\($region\) ) ]($style)'

[golang]
symbol = "î˜§"
# style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "î˜†"
# style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = "î˜ˆ"
# style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "îœ¸"
# style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%r"
# style = "bg:#1d2230"
format = '[ $time ïº ]($style)'
# format = '[[ $time ïº ](fg:#a0a9cb bg:#1d2230)]($style)'

# [fill]
# symbol = ' '

[memory_usage]
disabled = false
threshold = -1
symbol = ''
# style = 'fg:#f9cc6c'
format = '[ ${ram} ïƒ¤ î‚· ]($style)'

[shell]
unknown_indicator = '?'
# style = 'cyan bold'
disabled = false

[username]
show_always = true
# style_user = "cyan bold"
# style_root = "red bold"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
# style = "cyan bold"
format = '[@$hostname ]($style)'
disabled = false

[palettes.notakrista]
rosewater = "#ff3b00"
flamingo = "#ff7800"
pink = "#ff7800"
mauve = "#c7396d"
red = "#ff3b00"
maroon = "#7a001f"
peach = "#ff7800"
yellow = "#ffd500"
green = "#00ff00"
teal = "#00b5ac"
cyan = "#00ffea"
sky = "#00ffea"
sapphire = "#005aff"
blue = "#005aff"
lavender = "#c7396d"
text = "#ffffff"
subtext1 = "#d6d6d6"
subtext0 = "#b8b8b8"
overlay2 = "#919191"
overlay1 = "#707070"
overlay0 = "#4e4e4e"
surface2 = "#353535"
surface1 = "#242424"
surface0 = "#131313"
base = "#000000"
mantle = "#000000"
crust = "#000000"

